services:
  - type: web
    name: yash-world
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_STORAGE_BUCKET
        value: happybirthday-a287a.appspot.com
